// 無線局運用規則 別表第一号 １ 和文（e-Gov 法令 325M50080000017）
// Keep the published Iroha order; names are translation keys, not rendered labels.
export const WABUN_TABLE = [
  { char: 'イ', code: '.-', kind: 'kana', romaji: 'i' },
  { char: 'ロ', code: '.-.-', kind: 'kana', romaji: 'ro' },
  { char: 'ハ', code: '-...', kind: 'kana', romaji: 'ha' },
  { char: 'ニ', code: '-.-.', kind: 'kana', romaji: 'ni' },
  { char: 'ホ', code: '-..', kind: 'kana', romaji: 'ho' },
  { char: 'ヘ', code: '.', kind: 'kana', romaji: 'he' },
  { char: 'ト', code: '..-..', kind: 'kana', romaji: 'to' },
  { char: 'チ', code: '..-.', kind: 'kana', romaji: 'chi' },
  { char: 'リ', code: '--.', kind: 'kana', romaji: 'ri' },
  { char: 'ヌ', code: '....', kind: 'kana', romaji: 'nu' },
  { char: 'ル', code: '-.--.', kind: 'kana', romaji: 'ru' },
  { char: 'ヲ', code: '.---', kind: 'kana', romaji: 'wo' },
  { char: 'ワ', code: '-.-', kind: 'kana', romaji: 'wa' },
  { char: 'カ', code: '.-..', kind: 'kana', romaji: 'ka' },
  { char: 'ヨ', code: '--', kind: 'kana', romaji: 'yo' },
  { char: 'タ', code: '-.', kind: 'kana', romaji: 'ta' },
  { char: 'レ', code: '---', kind: 'kana', romaji: 're' },
  { char: 'ソ', code: '---.', kind: 'kana', romaji: 'so' },
  { char: 'ツ', code: '.--.', kind: 'kana', romaji: 'tsu' },
  { char: 'ネ', code: '--.-', kind: 'kana', romaji: 'ne' },
  { char: 'ナ', code: '.-.', kind: 'kana', romaji: 'na' },
  { char: 'ラ', code: '...', kind: 'kana', romaji: 'ra' },
  { char: 'ム', code: '-', kind: 'kana', romaji: 'mu' },
  { char: 'ウ', code: '..-', kind: 'kana', romaji: 'u' },
  { char: 'ヰ', code: '.-..-', kind: 'kana', romaji: 'wi' },
  { char: 'ノ', code: '..--', kind: 'kana', romaji: 'no' },
  { char: 'オ', code: '.-...', kind: 'kana', romaji: 'o' },
  { char: 'ク', code: '...-', kind: 'kana', romaji: 'ku' },
  { char: 'ヤ', code: '.--', kind: 'kana', romaji: 'ya' },
  { char: 'マ', code: '-..-', kind: 'kana', romaji: 'ma' },
  { char: 'ケ', code: '-.--', kind: 'kana', romaji: 'ke' },
  { char: 'フ', code: '--..', kind: 'kana', romaji: 'fu' },
  { char: 'コ', code: '----', kind: 'kana', romaji: 'ko' },
  { char: 'エ', code: '-.---', kind: 'kana', romaji: 'e' },
  { char: 'テ', code: '.-.--', kind: 'kana', romaji: 'te' },
  { char: 'ア', code: '--.--', kind: 'kana', romaji: 'a' },
  { char: 'サ', code: '-.-.-', kind: 'kana', romaji: 'sa' },
  { char: 'キ', code: '-.-..', kind: 'kana', romaji: 'ki' },
  { char: 'ユ', code: '-..--', kind: 'kana', romaji: 'yu' },
  { char: 'メ', code: '-...-', kind: 'kana', romaji: 'me' },
  { char: 'ミ', code: '..-.-', kind: 'kana', romaji: 'mi' },
  { char: 'シ', code: '--.-.', kind: 'kana', romaji: 'shi' },
  { char: 'ヱ', code: '.--..', kind: 'kana', romaji: 'we' },
  { char: 'ヒ', code: '--..-', kind: 'kana', romaji: 'hi' },
  { char: 'モ', code: '-..-.', kind: 'kana', romaji: 'mo' },
  { char: 'セ', code: '.---.', kind: 'kana', romaji: 'se' },
  { char: 'ス', code: '---.-', kind: 'kana', romaji: 'su' },
  { char: 'ン', code: '.-.-.', kind: 'kana', romaji: 'n' },
  { char: '゛', code: '..', kind: 'mark', name: 'wabun.dakuten' },
  { char: '゜', code: '..--.', kind: 'mark', name: 'wabun.handakuten' },
  { char: '1', code: '.----', kind: 'digit' },
  { char: '2', code: '..---', kind: 'digit' },
  { char: '3', code: '...--', kind: 'digit' },
  { char: '4', code: '....-', kind: 'digit' },
  { char: '5', code: '.....', kind: 'digit' },
  { char: '6', code: '-....', kind: 'digit' },
  { char: '7', code: '--...', kind: 'digit' },
  { char: '8', code: '---..', kind: 'digit' },
  { char: '9', code: '----.', kind: 'digit' },
  { char: '0', code: '-----', kind: 'digit' },
  { char: 'ー', code: '.--.-', kind: 'symbol', name: 'wabun.long_vowel' },
  { char: '、', code: '.-.-.-', kind: 'symbol', name: 'wabun.separator' },
  { char: '」', code: '.-.-..', kind: 'symbol', name: 'wabun.paragraph' },
  { char: '（', code: '-.--.-', kind: 'symbol', name: 'wabun.open' },
  { char: '）', code: '.-..-.', kind: 'symbol', name: 'wabun.close' },
];
export const WABUN_CHAR_TO_CODE = new Map(WABUN_TABLE.map(({ char, code }) => [char, code]));
export const WABUN_CODE_TO_CHAR = new Map(WABUN_TABLE.map(({ char, code }) => [code, char]));
export const WABUN_SAMPLES = ['モールス', 'イロハ', 'がっこう', 'サクラ サク'];
